language: node_js
node_js:
  - '8'
env:
  global:
    # doubleface GITHUB_TOKEN
    # to generate yours : travis encrypt GITHUB_TOKEN=<your_GITHUB_TOKEN> -r konnectors/cozy-konnector-generali
    - secure: "jfZVSNlF27yqLHX08+Ee7QX8/jyY72OCIeX8ScfWOjsX5VgAQAMg2MrJvGpzFX1P/1Kw99SOjw/cJUzCalJgMwj9B+7GSfMRdPtCEZVnrg65HYcHKZI92Ivp3MJni2ImcO/Buq9LZ+s7XMlbc18fIL/4MQV+juc7HIPZ6OkgoOZvB1GgGWEMbkmBPJLi0X6SSWwHYy8Gqx4ZErUOBeuQn2wMveACM3gjmRzHoBkgS8ziCv+AkZ1IR5sEoESZyx8TJTyzHQclBx8WWdLxfk7ofg7WsjHxoRrIOMqjxg3bAxVn7Ad0zJSlhc0/CM+2XmIVitwZO3Ons9F34iIPrL95VNjwI4hap66JseKM8WrC2ACdPgv+z4MIRlEGR7M6LUofBmie0BXCOnm/eintzuSj21Or3At+35ylBhqwonLX572NcZJ//xqQs13+rZJVcEwAg6jUqOrzACjZbQ/4SBW90LBQ4eWbsm7jrEcJs/2gYAnnsVW5Vp2FQjgOZpKrMtd0CrgZj5kspVGMIBV06kQLbvcvvvHh5YiOgbi1QTzVqpwI/Nba7rxkHo6Ojxjcu1A9MqG+YKD9zKKw1qMuIFg39iGsYDVlJhRyer36N22/fKWgM1XVpHtydqmc+Bs3lLTqnyRB7fTXweZx5g2yjjIRDzOcjFPnnqfrSU/AS02dd9c="
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn build
  - yarn lint
  - if [ $TRAVIS_SECURE_ENV_VARS = "true" ]; then yarn test; fi
deploy:
  - provider: script
    repo: konnectors/cozy-konnector-generali
    skip-cleanup: true
    script: yarn deploy
    on:
      branch: master
  - provider: script
    repo: konnectors/cozy-konnector-generali
    skip-cleanup: true
    script: yarn deploy:prod
    on:
      branch: prod
