language: node_js
node_js:
  - '8'
env:
  global:
    # doubleface GITHUB_TOKEN
    # to generate yours : travis encrypt GITHUB_TOKEN=<your_GITHUB_TOKEN> -r konnectors/cozy-konnector-generali
    - secure: "IxsSzZ8l6tGQH2E4Ej/nP0jrduJtFBGfBP5rxPU46TTYZqxf6rnkOYHNBS2lHZ31oun3ihYgqVHvWIWvkZAEUHntyBK6r8/oxFXkNjOtuWGxv4O5yn9Kdqqkb39LepSHPR7i/GdZXn3F3rfUjZvkxw9lsYYcQ6KGCNlGlXKrRazgn02ZZUovAf5d13v866okbV1R8a8kt2eyc3tpBFFhvGGHzN6Wp9PDhIsTJE9M2t/S3GwC1iVuQRaFNhqA4SV1+Gixs6HiMcN+01N0BNPUfEJp4C23+Mdwd6r1sg819cyZnAjwViRtAk7DMT7Mifyrgtc7JjnC2Y/TZtdOo8QdQRp4Mt9X9DxntcBGhVsG8PRkgmSh19Z+M+R9IQsIjrZfautKFiVhiHLNSRl8RVCG5G9AZy0HkNPufFULW+u/ohKK9LWMp6Z1y8aNeTOQPRb0s81HmfWWWNUWxk57dGt+tnV30EiMF3U4DeTKT/CzvRNKI1zjojf+FM7qEhSP/Jk3aSekeBvMekyRNFHCUgeAngj17To+YD9PfdaasUUuthX6X8Nlklcafi45a4PZniHTsVUWtg28aPTn7p4uIVV8RC3MG6yMI6eACMYO9aBo1jb68lbq/AGS5VbwEMsyVhiyB9Bu5St/ir8Dx/mPd4Ogdb2983I8thqZusrmR5rHuuY="
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn build
  - yarn lint
  - if [ $TRAVIS_SECURE_ENV_VARS = "true" ]; then yarn test; fi
deploy:
  - provider: script
    repo: konnectors/cozy-konnector-generali
    skip-cleanup: true
    script: yarn deploy
    on:
      branch: master
  - provider: script
    repo: konnectors/cozy-konnector-generali
    skip-cleanup: true
    script: yarn deploy:prod
    on:
      branch: prod
